spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql_db:3306/online_cinema
    username: user
    password: user
  sql:
    init:
      mode: always
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
